import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import { Itim } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { SidebarProvider } from "@/components/ui/sidebar";
import Sidepanel from "@/components/composites/Sidepanel/Sidepanel";
import Navbar from "@/components/composites/Navbar";


const itimSans = Itim({
  variable: "--font-itim",
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {





  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${itimSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SidebarProvider>
              <Sidepanel />
              <div className="w-full">
                <Navbar />
                {children}
              </div>
            </SidebarProvider>
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}